version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: polnyi-db
      MYSQL_USER: mish
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
  app:
    build: .
    image: lab4/latest
    container_name: app
    depends_on:
      - mysql
    ports:
      - "1489:1489"
    restart: "always"

volumes:
    mysql_data:
    mysql_config:
